### ISSUE TITLE
Missing Captive Portal, OTA and API

### ISSUE THREAD

**Issue by Goldwing1973** [sliwma/mysmarthome#2]
I tried to flash a iFan03 with the latest version of the ESPHome config, but after flashing Home Assistant couldn't connect to it.
It looks like it's missing the following lines

```
captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "PASS"

ota:
  password: "PASS"
```
